[package]
name = "aor"
version = "0.1.0"
authors = ["Moritz Grauel <mo@notadomain.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
